# Generated by Django 4.2.3 on 2023-07-30 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="username",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="email",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="password",
        ),
    ]
