# Generated by Django 4.2.3 on 2023-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_rename_username_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_auto_generated",
            field=models.BooleanField(default=False),
        ),
    ]
